cd /home/codespace/ttkerrr
lsof -ti:3000 | xargs -r kill -9 2>/dev/null || true
sleep 1

cat > public/js/app.js << 'APPJS'
let ws=null,autoRefreshInterval=null,streamingUsers=new Map(),currentUsers=[],players=new Map();
function connectWebSocket(){const p=location.protocol==='https:'?'wss:':'ws:';ws=new WebSocket(`${p}//${location.host}`);ws.onopen=()=>{console.log('✅ WebSocket connected');ws.send(JSON.stringify({type:'requestStatus'}))};ws.onmessage=(e)=>{const d=JSON.parse(e.data);if(d.type==='statusUpdate'){console.log('📡 Real-time status update');updateStatusDisplay(d.status)}};ws.onclose=()=>{console.log('🔌 Reconnecting...');setTimeout(connectWebSocket,3000)}}
async function loadUsers(){const r=await fetch('/api/users'),d=await r.json();currentUsers=d.users;renderUsersList()}
function renderUsersList(){const u=document.getElementById('usersList');if(!currentUsers.length){u.innerHTML='<div style="color:#666;padding:20px;text-align:center">No users</div>';return}u.innerHTML=currentUsers.map(n=>`<div class="user-tag"><span class="username">@${n}</span><button class="remove-btn"onclick="removeUser('${n}')">✕</button></div>`).join('')}
async function addUser(){const i=document.getElementById('newUsername'),u=i.value.trim();if(!u)return alert('Enter username');const r=await fetch('/api/users/add',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u})}),d=await r.json();if(d.success){currentUsers=d.users;renderUsersList();i.value='';updateStatus()}else alert(d.message)}
async function removeUser(u){if(!confirm(`Remove @${u}?`))return;const r=await fetch('/api/users/remove',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u})}),d=await r.json();if(d.success){currentUsers=d.users;renderUsersList();updateStatus()}}
async function performLogin(){const u=document.getElementById('loginUsername').value,p=document.getElementById('loginPassword').value;if(!u||!p)return alert('Enter credentials');const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u,password:p})}),d=await r.json();if(d.success){document.getElementById('loginModal').classList.add('hidden');await startMonitoring()}else alert('Login failed')}
async function skipLogin(){document.getElementById('loginModal').classList.add('hidden');await startMonitoring()}
async function startMonitoring(){const r=await fetch('/api/start',{method:'POST'}),d=await r.json();if(d.success){startAutoRefresh();connectWebSocket();updateStatus()}}
async function stopMonitoring(){await fetch('/api/stop',{method:'POST'});stopAutoRefresh();for(const[u]of streamingUsers)await stopStreamCapture(u);updateStatus()}
async function refreshStatus(){await fetch('/api/refresh',{method:'POST'});setTimeout(updateStatus,1000)}
async function startStreamCapture(u){if(streamingUsers.has(u)){console.log('Already loading',u);return}console.log('▶️ Starting:',u);streamingUsers.set(u,{loading:!0});const v=document.getElementById(`stream-${u}`);if(!v)return;v.innerHTML='<div class="stream-placeholder">⏳ Verifying live status...</div>';try{const r=await fetch(`/api/stream/start/${u}`,{method:'POST'}),d=await r.json();console.log('Response:',d);if(d.success&&d.originalUrl){console.log(`✅ ${d.streamType}:`,d.originalUrl);streamingUsers.set(u,{url:d.originalUrl,type:d.streamType,playing:!0});const vid=`video-${u}`;v.innerHTML=`<video id="${vid}"controls autoplay style="width:100%;height:100%;object-fit:contain;background:#000"></video><div style="position:absolute;top:10px;right:10px;background:rgba(255,0,80,0.9);padding:5px 10px;border-radius:5px;font-size:11px;font-weight:bold;z-index:10">⚠️ DIRECT</div>`;const video=document.getElementById(vid);if(!video){console.error('Video not found!');streamingUsers.delete(u);return}console.log('Init player:',d.streamType);if(d.streamType==='m3u8'){if(typeof Hls!=='undefined'&&Hls.isSupported()){console.log('Using HLS.js');const hls=new Hls();hls.loadSource(d.originalUrl);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,()=>{console.log('✅ Playing');video.play().catch(e=>console.log('Autoplay blocked'))});hls.on(Hls.Events.ERROR,(e,err)=>{console.error('HLS Error:',err);if(err.fatal){v.innerHTML=`<div class="stream-placeholder"style="color:#f66">❌ Stream expired<br><button class="btn btn-small btn-primary"onclick="startStreamCapture('${u}')"style="margin-top:10px">🔄 Retry</button></div>`;streamingUsers.delete(u)}});players.set(u,hls)}else if(video.canPlayType('application/vnd.apple.mpegurl')){video.src=d.originalUrl;video.play().catch(e=>console.log('Autoplay blocked'))}}else if(d.streamType==='flv'){if(typeof flvjs!=='undefined'&&flvjs.isSupported()){console.log('Using FLV.js');const flv=flvjs.createPlayer({type:'flv',url:d.originalUrl,isLive:!0,hasAudio:!0,hasVideo:!0,cors:!0});flv.attachMediaElement(video);flv.load();flv.play().catch(e=>console.log('Autoplay blocked'));flv.on(flvjs.Events.ERROR,(t,det)=>{console.error('FLV Error:',t,det);v.innerHTML=`<div class="stream-placeholder"style="color:#f66">❌ Stream expired<br><button class="btn btn-small btn-primary"onclick="startStreamCapture('${u}')"style="margin-top:10px">🔄 Retry</button></div>`;streamingUsers.delete(u)});players.set(u,flv);console.log('✅ FLV OK')}}}else{streamingUsers.delete(u);v.innerHTML=`<div class="stream-placeholder"style="color:#f66">❌ ${d.message||'Failed'}<br><small>User may have gone offline</small></div>`}}catch(e){streamingUsers.delete(u);if(v)v.innerHTML=`<div class="stream-placeholder"style="color:#f66">❌ ${e.message}</div>`}}
async function stopStreamCapture(u){console.log('⏹ Stop:',u);const p=players.get(u);if(p){try{if(p.destroy)p.destroy();else if(p.detachMediaElement)p.detachMediaElement()}catch(e){}players.delete(u)}await fetch(`/api/stream/stop/${u}`,{method:'POST'});streamingUsers.delete(u);const v=document.getElementById(`stream-${u}`);if(v)v.innerHTML='<div class="stream-placeholder">👆 Click Watch</div>'}
function startAutoRefresh(){if(autoRefreshInterval)clearInterval(autoRefreshInterval);autoRefreshInterval=setInterval(updateStatus,15000)}
function stopAutoRefresh(){if(autoRefreshInterval){clearInterval(autoRefreshInterval);autoRefreshInterval=null}}
function updateStatusDisplay(statusData){Object.entries(statusData).forEach(([user,info])=>{const card=document.querySelector(`#stream-${user}`)?.closest('.stream-card');if(!card)return;const badge=card.querySelector('.live-badge');if(badge){badge.className=`live-badge ${info.isLive?'active':'inactive'}`;badge.innerHTML=`<span class="indicator"></span>${info.isLive?'LIVE':'Offline'}`}const viewers=card.querySelectorAll('.info-value')[1];if(viewers)viewers.textContent=info.viewers.toLocaleString();const lastCheck=card.querySelectorAll('.info-value')[2];if(lastCheck)lastCheck.textContent=new Date(info.lastChecked).toLocaleTimeString();if(info.isLive){card.classList.add('live')}else{card.classList.remove('live')}})}
async function updateStatus(){const r=await fetch('/api/status'),d=await r.json();const sb=document.getElementById('monitorStatus');sb.className=d.isMonitoring?'status-badge monitoring':'status-badge offline';sb.innerHTML=d.isMonitoring?'🟢 Monitoring':'⚫ Off';const sg=document.getElementById('streamsGrid');if(!Object.keys(d.status).length){sg.innerHTML='<div style="color:#666;padding:40px;text-align:center;font-size:1.2em">Add users</div>';return}const existing=sg.querySelectorAll('.stream-card');if(existing.length!==Object.keys(d.status).length){sg.innerHTML=Object.entries(d.status).map(([user,info])=>createCard(user,info)).join('')}else{updateStatusDisplay(d.status)}const lc=document.getElementById('logsContent');lc.innerHTML=d.logs.slice(-50).reverse().map(l=>`<div class="log-entry"><div class="log-time">${l.time}</div><span class="log-level ${l.level}">[${l.level.toUpperCase()}]</span>${l.username?`<span style="color:#f50">@${l.username}</span>: `:''}<span>${l.message}</span></div>`).join('');const sc=document.getElementById('statsContent');sc.innerHTML=`<div class="stat-row"><span>Total:</span><strong>${d.stats.totalUsers}</strong></div><div class="stat-row"><span>Live:</span><strong style="color:#4c0">${d.stats.liveCount}</strong></div><div class="stat-row"><span>Watching:</span><strong style="color:#f50">${streamingUsers.size}</strong></div>`}
function createCard(u,info){const si=streamingUsers.get(u),isP=si&&si.playing;return`<div class="stream-card ${info.isLive?'live':''}"><div class="stream-header"><a href="https://www.tiktok.com/@${u}" target="_blank" rel="noopener noreferrer" class="stream-username" style="text-decoration:none;color:inherit;display:flex;align-items:center;gap:8px;transition:all .3s"><span>@${u}</span><svg style="width:16px;height:16px;opacity:0.6" fill="currentColor" viewBox="0 0 20 20"><path d="M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z"/><path d="M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z"/></svg></a><div class="live-badge ${info.isLive?'active':'inactive'}"><span class="indicator"></span>${info.isLive?'LIVE':'Offline'}</div></div><div class="stream-video"id="stream-${u}"style="position:relative">${info.isLive?(isP?'<div class="stream-placeholder">🎬 Playing...</div>':'<div class="stream-placeholder">👆 Click Watch 🎵</div>'):'<div class="stream-placeholder">❌ Offline</div>'}</div><div class="stream-info"><div class="info-item"><div class="info-label">Status</div><div class="info-value">${info.isLive?'🔴 LIVE':'⚫ Offline'}</div></div><div class="info-item"><div class="info-label">Viewers</div><div class="info-value">${info.viewers.toLocaleString()}</div></div><div class="info-item"><div class="info-label">Last Check</div><div class="info-value"style="font-size:.9em">${new Date(info.lastChecked).toLocaleTimeString()}</div></div></div>${info.isLive?`<div class="stream-controls">${isP?`<button class="btn btn-warning btn-small"onclick="stopStreamCapture('${u}')">⏹ Stop</button>`:`<button class="btn btn-success btn-small"onclick="startStreamCapture('${u}')">🎬 Watch Stream</button>`}</div>`:''}</div>`}
async function clearLogs(){if(!confirm('Clear?'))return;await fetch('/api/logs/clear',{method:'POST'});updateStatus()}
loadUsers();updateStatus();
APPJS

# Add hover effect to CSS
cat >> public/css/styles.css << 'ADDCSS'

/* Clickable username styling */
.stream-username:hover {
  color: #00f2ea !important;
  transform: translateX(3px);
}

.stream-username svg {
  transition: opacity 0.3s;
}

.stream-username:hover svg {
  opacity: 1 !important;
}
ADDCSS

echo "✅ Added clickable usernames!"
echo "   • Click username to open TikTok profile in new tab"
echo "   • Hover effect shows it's clickable"
echo "   • External link icon appears"
echo ""
echo "Starting server..."
node server.js
